config/routes.rb
Egocentric::Application.routes.draw do

  opinio_model

  resources :guides do
    opinio
    member do
      get :select
      get :reload_comments
      post :rate
      get :save
    end
  end

  post "avatar" => "users#update_avatar", :as => "avatar"
  post "like" => "guides#like", :as => "like"
  get "welcome" => "guides#welcome", :as => "welcome"
  get "recent" => "guides#recent", :as => "recent"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users
  resources :sessions

  root :to => 'guides#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  opinio
  has_many :likes
  attr_accessible :likes
  after_create :add_activity
  before_destroy :remove_activity

  def add_activity
    type = self.commentable.type == Guide ? Activity::POSTED_COMMENT : Activity::REPLIED_COMMENT
    Activity.add(self.owner, type, self)
  end

  def remove_activity
    Activity.find_by_target_id(self.id).delete
  end
end

app/views/opinio/comments/_comment.html.haml
- reply = defined?(reply) ? reply : false
%li{:id => "comment_#{comment.id}"}
  .comment
    .likes
      .count
        = comment.likes.count
      .like
        %a{:id => "#{comment.id}", :href => "#", :class => "#{current_user && current_user.already_likes?(comment) ? "active" : ""}"} like
    .content
      %span
        By 
        %a{:href => "#"} #{comment.owner.username}
        - if current_user && (current_user.username == comment.owner.username || current_user.role == "admin")
          = link_to '(delete)', comment_path(comment), :method => :delete, :remote => true
        on
        = format_date(comment.created_at)
      %p{:class => "#{comment.owner.role == "admin" ? "admin" : ""}"}
        = comment.body
      %a.line{:href => "#"} 
        %img{:src => "/assets/line.png"}
      - if Opinio.accept_replies && !reply
        %span.reply= link_to t("opinio.reply", :default => "Reply"), reply_comment_path(comment), :remote => true
  - if Opinio.accept_replies && !reply
    %ul.replies{:id => "comment_#{comment.id}_replies"}
      = render :partial => "opinio/comments/comment", :collection => comment.comments, :locals => {:reply => true}

app/views/opinio/comments/_comments.html.haml
.comments
  .header
    .left
      .number= @guide.all_comments.count
      .sorting
        %span.sort Sort by:
        %a#likes{:href => "#", :class => "#{"active" if params[:filter] == "likes"}"} Most Liked
        %a#date{:href => "#", :class => "#{"active" if params[:filter] != "likes"}"}  Newest
    .right
      %span.sort.collapse Collapse:
      %a.collapse-all{:href => "#"} All
      %a.collapse-none{:href => "#"} None
    %span.ajax
  %ul#comments
    - unless comments.empty?
      = render :partial => 'opinio/comments/comment', :collection => comment_sort(comments)
    - else
      %li#no_comments= t 'opinio.no_comments_found', :default => "No comments found"

app/views/opinio/comments/_new.html.haml
.comments.new
  .header
    - if send(Opinio.current_user_method)
      %span.sort Post a comment
      %span.reply Reply
  .textarea
    - if send(Opinio.current_user_method)
      = form_for Comment.new, :remote => true do |f|
        = f.text_area :body, :id => "Comment"
        = hidden_field_tag :commentable_id_org, commentable.id
        = hidden_field_tag :commentable_type_org, commentable.class.base_class.name.to_s
        = hidden_field_tag :commentable_id, commentable.id
        = hidden_field_tag :commentable_type, commentable.class.base_class.name.to_s
        = f.submit "Submit", :class => "btn reply-submit"
        %a.btn.cancel{:href => "#"} Cancel
    - else
      %p
        Must be logged in to comment.

app/views/opinio/comments/create.js.erb
$('#no_comments').fadeOut()
<% if @comment.valid? %>
  <% if @reply %>
    if($('#comment_<%= @comment.commentable_id %> ul').length == 0)
      $('#comment_<%= @comment.commentable_id %>').prepend('<ul id="comment_<%= @comment.commentable_id %>_replies" class="replies"></ul>')
    $('#comment_<%= @comment.commentable_id %>_replies').prepend("<%= escape_javascript( render @comment, :locals => {:reply => @reply} ) %>")
    $('#commentable_id').val('<%= @comment.commentable.commentable_id %>')
    $('#commentable_type').val('<%= @comment.commentable.commentable_type %>')
    $('#new_comment textarea').val('')
    setTimeout(function() { $('html, body').animate({scrollTop: $('#comment_<%= @comment.id %>').offset().top - 80 }, 200);}, 500);
  <% else %>
    $('#comments').prepend("<%= escape_javascript( render @comment, :locals => {:reply => @reply} ) %>")
    setTimeout(function() { $('html, body').animate({scrollTop: $('#comment_<%= @comment.id %>').offset().top - 80 }, 200);}, 500);
    $('#new_comment textarea').val('')
  <% end %>
<% else %>
<% end %>

app/views/opinio/comments/destroy.js.erb
jQuery('#comment_<%= @comment.id %>').remove();
if (jQuery('#comments').children('li:not(#no_comments)').length == 0) {
  jQuery('#no_comments').fadeIn();
}
//jQuery('#comments').prepend("<%= escape_javascript(flash[:notice]) %>");
//jQuery('#comments').prepend("<%= escape_javascript(flash[:error]) %>");

app/views/opinio/comments/index.html.haml
%h1 Comments
= paginate @comments
= render :partial => "opinio/comments/comments", :locals => { :comments => @comments }
= paginate @comments

app/views/opinio/comments/reply.js.erb
$("#commentable_id").val('<%= @commentable_id %>')
$("#commentable_type").val('<%= @commentable_type %>')
$("#new_comment textarea").val('')
$("#new_comment textarea").focus()
$(".comments.new .reply, .cancel").fadeIn();
$("#new_comment .btn").live('click', function(e) {
  $(".comments.new .reply, .comments.new .cancel").fadeOut()
});
$('.cancel').live('click', function(e) {
  $(".comments.new .reply, .cancel").fadeOut();
  $("#commentable_id").val($("#commentable_id_org").val());
  $("#commentable_type").val($("#commentable_type_org").val());
  $("#new_comment textarea").val('')
  $("#new_comment textarea").focus()
  return false;
});