config/routes.rb
Egocentric::Application.routes.draw do

  opinio_model

  resources :guides do
    opinio
    member do
      get :select
      get :reload_comments
      post :rate
      get :save
    end
  end

  post "avatar" => "users#update_avatar", :as => "avatar"
  post "like" => "guides#like", :as => "like"
  get "welcome" => "guides#welcome", :as => "welcome"
  get "recent" => "guides#recent", :as => "recent"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users
  resources :sessions

  root :to => 'guides#index'
end

app/models/guide.rb
class Guide < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy

  validates_presence_of :user 
  validates_presence_of :name
  validates_presence_of :category
  validates_uniqueness_of :name

  attr_accessible :name, :body, :category, :user, :video, :guide_type, :map

  ajaxful_rateable :stars => 5, :dimensions => [:rating]
  opinio_subjectum

  after_create :add_activity
  before_destroy :remove_activity

  def is_egocentric?
    true if self.user.role == "egocentric"
  end

  def is_featured?
    true if self.guide_type == "featured"
  end

  def add_activity
    Activity.add(self.user, Activity::POSTED_GUIDE, self)
  end  

  def all_comments
    self.comments.collect { |c| [c] + c.comments }.flatten
  end

  def more_from_category
    Guide.find_all_by_category(self.category, :limit => 4, :conditions => ["id != ?", self.id])
  end

  def self.all_categories
    Guide.select(:category).group(:category).collect { |g| g.category }
  end

  def self.all_maps
    Guide.select(:map).group(:map).collect { |g| g.map }
  end 

   def remove_activity
    Activity.find_by_target_id(self.id).delete if Activity.find_by_target_id(self.id)
  end 
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  include Opinio::Controllers::Helpers

  before_filter :authorize, :only => [:create, :update, :delete, :new, :rate]
  before_filter :find_guide, :except => [:index]

  def index
    if params[:filter] == "rating"
      @guides = Guide.all.sort_by { |g| g.rate_average(false, :rating) }.reverse
    else
      @guides = Guide.find(:all, :order => "created_at DESC")
    end

    @featured = Guide.where(:guide_type => "featured").limit(5)
  end 

  def welcome
    @featured = case
    when params[:welcome] == "egocentric"
      Guide.where(:guide_type => "approved").limit(5)
    when params[:welcome] == "top"
      Guide.first(5).sort_by { |g| g.rate_average(false, :rating)}.reverse
    else
      Guide.where(:guide_type => "featured").limit(5)
    end

    respond_to do |format|
      format.js
    end
  end

  def recent
    respond_to do |format|
      format.js  
    end
  end

  def destroy
    @guide.destroy
    redirect_to "/guides"
  end

  def update
    updates = params[:guide]
    updates['avatar'] = nil if updates['avatar'] == "url of image" || updates['avatar'] == ""
    updates['video'] = nil if updates['video'] == "url of youtube video" || updates['video'] == ""
    @guide.update_attributes(updates)
    render :json => { "status" => "success",
                       "redirect" => guide_path(@guide)}
  end

  def create
    @guide = Guide.new(params[:guide])
    @guide.avatar = nil if @guide.avatar == "url of image" || @guide.avatar == ""
    @guide.video = nil if @guide.video == "url of youtube video" || @guide.video == ""
    @guide.user = current_user
    if @guide.save
      render :json => { "status" => "success",
                        "redirect" => "/guides/#{@guide.id}"}
    else
      render :json => { "status" => "failure",
                        "errors" => @guide.errors.full_messages}
    end
  end 

  def like
    @comment = Comment.find(params[:comment_id]) if params[:comment_id]
    if current_user.already_likes?(@comment)
      @like = @comment.likes.find_by_user_id(current_user.id)
      @like.destroy
      render :json => { "status" => "failure", "count" => @comment.likes.count }
    else
      @like = Like.create(:comment => @comment, :user => current_user)
      if @like
        render :json => { "status" => "success", "count" => @comment.likes.count }
      else
        render :json => { "status" => "failure" }
      end
    end
  end

  def select
    @guide.guide_type = params[:select] ? params[:select] : nil
    @guide.save
    redirect_to "/guides"
  end

  def rate
    @guide = Guide.find(params[:id])
    @guide.rate(params[:stars], current_user, params[:dimension])

    respond_to do |format|
      format.js 
    end
  end

  def reload_comments
    @guide = Guide.find(params[:id])
    render :partial => "comments", :layout => false
  end 

private
  
  def find_guide
    @guide = Guide.find(params[:id]) if params[:id]
  end

end

app/helpers/guides_helper.rb
module GuidesHelper
end 

app/views/guides/_comments.html.haml
= comments_for @guide

app/views/guides/_guides.html.haml
%ul#guides
  - @guides.each do |guide|
    %li{:class => "#{guide.category} #{guide.map if guide.map}", :"data-rating" => "#{guide.rate_average}", :"data-date" => "#{format_date(guide.created_at)}"}
      %a{:href => guide_path(guide), :style => "display: block;"}
        .name
          %strong= truncate(guide.name, 51)
        .meta
          by 
          %strong #{guide.user.username} 
          on #{format_date(guide.created_at)}
          - if guide.guide_type != nil
            %div{:class => guide.guide_type}= guide.guide_type
      .rating
        = ratings_for guide, :static, :dimension => :rating

app/views/guides/_leaderboard.html.haml
.span4.leaderboard
  .header
    %span leaderboards
  .body
    %ul.leaderboard
      - @user_leaders.collect do |u|
        - user = User.find_by_username(u.username)
        %li
          %span.username
            %a{:href => "#"}= user.username
          %span.count= u.guides_count
          %span.bar{:style => "width: #{bar_width(u.guides_count)}%"} 

app/views/guides/_rating.html.haml
= ratings_for @guide, current_user, :show_user_rating => true, :dimension => :rating

app/views/guides/_recent.html.haml
%ul.activities
  - Activity.all.each do |a|
    %li
      != a.to_words 

app/views/guides/edit.html.haml
.guides.row
  .alert.alert-error
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
  %div{:class => "guide-#{@guide.id}"}
  .page.span9
    .header.no-avatar
      %input.name{:value => "#{@guide.name}"}
    .video
      %a.btn.remove-video{:href => "#"} 
        %i.icon.icon-minus
      %a.btn.add-video{:href => "#"} 
        %i.icon.icon-plus
      %input.video-url{:value => "url of youtube video"}
    %iframe.youtube{:style => "display: none;", :allowfullscreen => "", :frameborder => "0", :height => "500", :src => "", :width => "100%"}
    .body
      %textarea
        = @guide.body
       
  .sidebar.span3
    %ul.nav
      %li.nav-header
        Date
      %li.date
        = format_date(Date.today)
      %li.nav-header
        Category
      %li.categories
        %select#guide_category{:name => "guide[category]"}
          %option{:value => ""}
          - guide_categories.each do |c|
            %option{:value => "#{c}", :selected => ("true" if @guide.category == c) }= c.capitalize
      - if @guide.map 
        %li.nav-header
          Map
        %li.categories
          %select#guide_map{:name => "guide[map]"}
            %option{:value => ""}
            - maps.each do |c|
              %option{:value => "#{c}", :selected => ("true" if @guide.map == c) }= c.capitalize 
      %li
        %a.btn.preview{:href => "#"} Preview
      %li
        = link_to "Delete", guide_path(@guide.id), :method => :delete, :class => "btn delete"
      %li
        %a.btn.save{:href => "#"} Save
    %ul.nav.cheats
      %li.intro
        The editor uses <strong>Markdown</strong>, a text-to-HTML tool. Here is a cheat sheet to help you.
      %li 
        .element header
        .cheat #Header Text
      %li 
        .element list
        .cheat * list item
      %li 
        .element blockquote
        .cheat > quote text
      %li 
        .element bold
        .cheat **bold words**
      %li 
        .element italics
        .cheat *italic words* 
      %li 
        .element links
        .cheat [Name](http://...com)
      %li 
        .element image
        .cheat ![text](http://../img.png)
      %li 
        .element horizontal line
        .cheat ***  

app/views/guides/index.html.haml
.guides.guide
  .row.top
    .span4.promotion
      .header
        %span Welcome 
      .body
        #promo-slider.carousel
          .carousel-inner
            %a.ad-tip{:href => "#", :rel => "tooltip", :title => "Coming soon!"}
              .item.ad.active

    .span4.promotion
      .header
        %span{:id => "guide-title"} GUIDES
        %span.leaders
          = link_to "Top", {:controller => "guides", :action => "welcome", :welcome => "top"}
        %span.leaders
          = link_to "Approved", {:controller => "guides", :action => "welcome", :welcome => "egocentric"}
        %span.leaders
          = link_to "Featured", {:controller => "guides", :action => "welcome", :welcome => "featured"}, {:class => "active"}
        .ajax
      #featured.body
        = render "featured"

    .span4.recent
      .header
        %span Recent activity
        .ajax
      #recent.body
        = render "recent"
  .row
    .sidebar.scroll.index.span3
      %ul.nav
        %li.top
        %li.meta
          .left 
            Sort by
          .right
            = link_to "Date", {:controller => "guides", :action => "index", :filter => "date"}, {:class => "filter active"}
            = link_to "Rating", {:controller => "guides", :action => "index", :filter => "rating"}, {:class => "filter"} 
        %li.search
          %input.searchbox
        %li.list
          %div
            %h1 Categories
            %ul#source
              %li
                %a.all.active{:href => "#"} All
              - Guide.all_categories.each do |cat|
                %li
                  %a{:href => "#", :class => "#{cat}"} #{cat.capitalize}  
                  - if cat == "capping"
                    - if Guide.all_maps.count > 0
                      %ul
                        - Guide.all_maps.each do |map|
                          %li
                            %a{:href => "#", :class => "#{map}"} #{map.gsub(/\b\w/){$&.upcase}}  
    .guide-list.span9
      .header
        %span.title All Guides
        %span.count= Guide.find(:all).count
        %span.ajax 
      .all-guides 
        .no-guides
          No guides are found.
        = render "guides"

app/views/guides/index.js.erb
$(".all-guides").html("<%= escape_javascript(render("guides")) %>");
$('.ajax').fadeOut();

app/views/guides/new.html.haml
.guides.row
  .alert.alert-error
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
  .page.guide-new.span9
    .header.no-avatar
      %input.name{:value => "Name of guide"}
    .video
      %a.btn.remove-video{:href => "#"} 
        %i.icon.icon-minus
      %a.btn.add-video{:href => "#"} 
        %i.icon.icon-plus
      %input.video-url{:value => "url of youtube video"}
    %iframe.youtube{:style => "display: none;", :allowfullscreen => "", :frameborder => "0", :height => "500", :src => "", :width => "100%"}
    .body
      %textarea{:autofocus => ""} 

  .sidebar.span3
    %ul.nav
      %li.top
      %li.meta
        .left
          Date
        .right
          = format_date(Date.today)
      %li.nav-header
        Category
      %li.categories
        %select#guide_category{:name => "guide[category]"}
          %option{:value => ""}
          - guide_categories.each do |c|
            %option{:value => "#{c}"}= c.capitalize
      %li.nav-header
        Map
      %li.categories
        %select#guide_map{:name => "guide[map]"}
          %option{:value => ""}
          - maps.each do |c|
            %option{:value => "#{c}"}= c.capitalize 
      %li
        %a.btn.preview{:href => "#"} Preview
      %li
        %a.btn.submit{:href => "#"} Submit
    %ul.nav.cheats
      %li.intro
        The editor uses <strong>Markdown</strong>, a text-to-HTML tool. Here is a cheat sheet to help you.
      %li 
        .element header
        .cheat #Header Text
      %li 
        .element list
        .cheat * list item
      %li 
        .element blockquote
        .cheat > quote text
      %li 
        .element bold
        .cheat **bold words**
      %li 
        .element italics
        .cheat *italic words* 
      %li 
        .element links
        .cheat [Name](http://...com)
      %li 
        .element image
        .cheat ![text](http://../img.png)
      %li 
        .element horizontal line
        .cheat *** 

app/views/guides/rate.js.erb
$("#rates #<%= @guide.wrapper_dom_id(params) %>").html("<%= escape_javascript(ratings_for(@guide, params.merge(:wrap => false))) %>");
$("#average #<%= @guide.wrapper_dom_id(params) %>").html("<%= escape_javascript(ratings_for(@guide, params.merge(:show_user_rating => false, :force_static => true, :wrap => false))) %>");

app/views/guides/recent.js.erb
$("#recent").html("<%= escape_javascript(render("recent")) %>");
$('.ajax').fadeOut(); 

app/views/guides/reload_comments.html.haml
= comments_for @guide

app/views/guides/show.html.haml
.guides.guide.row
  .span9
    .page
      .header.no-avatar
        %h1= @guide.name
      - if @guide.video
        %iframe.youtube{:allowfullscreen => "", :frameborder => "0", :height => "500", :src => "http://www.youtube.com/embed/#{@guide.video}", :width => "100%"}
      - if @guide.body != ""
        .body.show
          != render_markdown(@guide.body)
    .comments#comment-list
      = comments_for @guide

  .sidebar.scroll.span3
    - if current_user && (current_user.username == @guide.user.username || current_user.role == "egocentric")
      .admin
        %a.btn.edit{:href => edit_guide_path(@guide.id)} Edit
        = link_to "Delete", guide_path, :method => :delete, :class => "btn delete"
    - if current_user && current_user.role == "egocentric"
      .admin.type
        = link_to "None", select_guide_path(@guide.id), :class => "btn"
        = link_to "Approve", select_guide_path(@guide.id, :select => "approved"), :class => "btn"
        = link_to "Feature", select_guide_path(@guide.id, :select => "featured"), :class => "btn"
    %ul.nav
      %li.top
      %li.meta
        .left 
          Author
        .right
          %a{:href => "#"}
            = @guide.user.username
      %li.meta
        .left Date
        .right
          = format_date(@guide.created_at)
      %li.meta
        .left Category
        .right
          = @guide.category.capitalize
      - if !(@guide.map == "")
        %li.meta
          .left Map
          .right
            = @guide.map.gsub(/\b\w/){$&.upcase}
      - if @guide.more_from_category != []
        %li.list
          %div 
            %h1 More from #{@guide.category}
            %ul
              - @guide.more_from_category.each do |g|
                %li
                  %a{:href => guide_path(g)}
                    != truncate(g.name, 30)
      %li.sidebar-comment.meta
        .left Comments
        .right 
          %span.comments= @guide.all_comments.count 
      %li.rating
        .left rating
        #average.right
          = ratings_for @guide, :static, :dimension => :rating
      %li.rating
        .left rate
        #rates.right
          - if current_user
            = ratings_for @guide, :show_user_rating => true, :dimension => :rating
          - else
            %span Must be logged in

app/views/guides/welcome.js.erb
$("#featured").html("<%= escape_javascript(render("featured")) %>");
$('.ajax').fadeOut(); 